if: tag IS blank

language: node_js
node_js:
- '10'

env: 
  - CODECOV_TOKEN="a282fbc6-9734-4f21-83d8-ef21d8d176e4"
  
cache:
  directories:
    - node_modules

before_install:
  - npm root -g
  - npm i rollup typescript eslint nyc
  - npm install


install: true

script:
  - npm run build
  - npm run test

after_success:
  - npm run cov:coveralls

