environment:
  matrix:
    - nodejs_version: "10"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm root -g
  - npm i rollup typescript eslint nyc
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run test

on_success:
  - npm run cov:coveralls

build: off
deploy: off
skip_tags: true

