name: Node.js CI

on: [push, pull_request]

jobs:
  Runner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10, 12]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i rollup typescript eslint nyc
        npm install
    - name: Continuous integration
      run: |
        npm run build
        npm run test
    - name: Code Coverage
      run: npm run cov:coverall
      env:
        CI: true
